existingSecret: overleaf-secrets

overleaf:
  appName: "Overleaf Local"
  siteUrl: "http://overleaf.lan"

  emailConfirmationDisabled: true

  maxUploadSizeMb: 100
  historyRestore: true

  templateGallery:
    enabled: true

persistence:
  size: 20Gi

nodeSelector:
  kubernetes.io/hostname: am-wanderer

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: overleaf.lan
      paths:
        - path: /
          pathType: Prefix


mongodb:
  persistence:
    size: 8Gi
  nodeSelector:
    kubernetes.io/hostname: am-wanderer

redis:
  persistence:
    size: 2Gi
  nodeSelector:
    kubernetes.io/hostname: am-wanderer
