---

- name: Update all packages
  hosts: "*"
  become: true
  roles:
    - os_base

- name: Prepare node for k3s
  hosts: "*"
  become: true
  roles:
    - k3s_prereq

- name: Set up k3s server
  hosts: k8s_master
  become: true
  roles:
    - role: k3s
      k3s_node_type: server

- name: Set up k3s agents
  hosts: k8s_worker
  become: true
  roles:
    - role: k3s
      k3s_node_type: agent

- name: Set up bonded network with Wi-Fi failover
  hosts: wifi
  become: true
  roles:
    - wifi
