- name: main | Update all packages and check if a reboot is required
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/{{ ansible_facts['os_family'] }}.yaml"

- name: Reboot if required
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: __os_base_reboot_required | default(false)
